name: storybook_dart
description: storybook_dart
version: 0.0.1
homepage: https://github.com/leanflutter/storybook_dart/tree/main/packages/storybook_dart

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
