name: preview_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  storybook_dart: ^0.1.0
  storybook_dart_annotation: ^0.1.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.2
  storybook_dart_generator: ^0.1.0

flutter:
  uses-material-design: true
