name: storybook_dart_generator
description: storybook_dart_generator
version: 0.0.3
homepage: https://github.com/leanflutter/storybook_dart/tree/main/packages/storybook_dart_generator

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  analyzer: ^6.2.0
  build: ^2.0.0
  build_config: ">=0.4.4 <2.0.0"
  code_builder: ^4.4.0
  flutter:
    sdk: flutter
  glob: ^2.1.2
  path: ^1.8.2
  source_gen: ^1.0.0
  source_helper: ^1.3.0
  storybook_dart_annotation: ^0.0.2

dev_dependencies:
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter
  mostly_reasonable_lints: ^0.1.2
